sudo: false
language: scala
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
script:
  - "sbt clean test:compile"
  - "sbt coverage test"
  - "sbt coverageReport coverageAggregate"
after_success: "sbt coveralls"